# 记录发布容器镜像的仓库登录信息

# 每一项的内容：
# 仓库名
# - 登录名
# - 登录密码

docker.io:
  - LOGIN_DOCKER_USER
  - LOGIN_DOCKER_PASSWD

quay.io:
  - LOGIN_QUAY_USER
  - LOGIN_QUAY_PASSWD

hub.oepkgs.net:
  - LOGIN_OEPKGS_USER
  - LOGIN_OEPKGS_PASSWD