[global]
debug = True
workflow_type = Github Actions
# openai token (siliconflow suggested)
llm_token = 

[Github Actions]
owner_name =
repo_name = 
repo_url = 
runner = ubuntu-24.04

[docker]
repository = 

